
package com.OG.Views;

import com.OG.Controller.Controldor_VentanaC_dihibridos;

/**
 *
 * @author acer
 */
public class VentanaC_Dihibridos extends javax.swing.JFrame {
   
    private Controldor_VentanaC_dihibridos Dh;
            
    /**
     * Creates new form VentanaC_Dihibridos
     */
    public VentanaC_Dihibridos() {
        initComponents();
        Iniciar_VentanaDihibrida();
        
    }

    public void Iniciar_VentanaDihibrida(){
     Dh = new Controldor_VentanaC_dihibridos(this);
     retornarButton.addActionListener(Dh);
    
    }
    
    
    
    
    public void showChild(ventana_principal ventanap, boolean b) {
      ventanap.setVisible(b);
       ventanap.setLocationRelativeTo(null);
       this.dispose();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Cruses_DihibridosPanel = new javax.swing.JPanel();
        retornarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Cruses_DihibridosPanel.setBackground(new java.awt.Color(102, 255, 102));
        Cruses_DihibridosPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        Cruses_DihibridosPanel.setToolTipText("Cruses Dihibridos ");

        retornarButton.setBackground(new java.awt.Color(102, 255, 102));
        retornarButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        retornarButton.setForeground(new java.awt.Color(0, 0, 0));
        retornarButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\atras.png")); // NOI18N
        retornarButton.setText("Menu de cruses");
        retornarButton.setActionCommand("retornar");
        retornarButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout Cruses_DihibridosPanelLayout = new javax.swing.GroupLayout(Cruses_DihibridosPanel);
        Cruses_DihibridosPanel.setLayout(Cruses_DihibridosPanelLayout);
        Cruses_DihibridosPanelLayout.setHorizontalGroup(
            Cruses_DihibridosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Cruses_DihibridosPanelLayout.createSequentialGroup()
                .addGap(0, 214, Short.MAX_VALUE)
                .addComponent(retornarButton))
        );
        Cruses_DihibridosPanelLayout.setVerticalGroup(
            Cruses_DihibridosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cruses_DihibridosPanelLayout.createSequentialGroup()
                .addComponent(retornarButton)
                .addGap(0, 379, Short.MAX_VALUE))
        );

        getContentPane().add(Cruses_DihibridosPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cruses_DihibridosPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton retornarButton;
    // End of variables declaration//GEN-END:variables

    
}
