
package com.OG.Views;
 
import com.OG.Controller.Controlador_VentanaC_MonoHibridos;
import javax.swing.JOptionPane;


/**
 *
 * @author Osmar 
 */
public class VentanaC_Monohibrida extends javax.swing.JFrame {
    
private Controlador_VentanaC_MonoHibridos CT;
    /**
    * Creates new form VentanaC_Monohibrida
    */
    public VentanaC_Monohibrida() {
        initComponents();
        Iniciar_VentanaMonoHibrida();
    }

  
 
   public void Iniciar_VentanaMonoHibrida()
   {
     CT = new Controlador_VentanaC_MonoHibridos(this); 
     retornoButton.addActionListener(CT);
      ideaButton.addActionListener(CT);

   }
    
    
    
   public void showChild(ventana_principal ventanap, boolean b) 
     { 
     ventanap.setVisible(b);
     ventanap.setLocationRelativeTo(null);
      this.dispose();
     
     }          
    

     public void showChild() {
      JOptionPane.showMessageDialog(null, "El valor de la U es valor universal"
              + "\n puede ser cualquier tipo de sindrome"
              + "\nEjemplo Daltonismo  D = U ");

    }

    
    
    
    
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrusesMonoHibridoPanel = new javax.swing.JPanel();
        retornoButton = new javax.swing.JToggleButton();
        MujerLabel = new javax.swing.JLabel();
        BaronLabel = new javax.swing.JLabel();
        ContenedorChecboxPanel = new javax.swing.JPanel();
        noportadoraCheckBox = new javax.swing.JCheckBox();
        sindromeCheckBox = new javax.swing.JCheckBox();
        portadoraCheckBox = new javax.swing.JCheckBox();
        ContenedorChecbox2Panel = new javax.swing.JPanel();
        sindromeRadioButton = new javax.swing.JRadioButton();
        sanoRadioButton = new javax.swing.JRadioButton();
        ContendorPunerPanel = new javax.swing.JPanel();
        SepadorLabel = new javax.swing.JLabel();
        SexoFLabel = new javax.swing.JLabel();
        SexoMLabel = new javax.swing.JLabel();
        CromosaMLabel3 = new javax.swing.JLabel();
        CromosaMLabel1 = new javax.swing.JLabel();
        CromosaMLabel2 = new javax.swing.JLabel();
        CromosaMLabel = new javax.swing.JLabel();
        CromosaMLabel4 = new javax.swing.JLabel();
        CromosaMLabel5 = new javax.swing.JLabel();
        CromosaMLabel6 = new javax.swing.JLabel();
        CromosaMLabel7 = new javax.swing.JLabel();
        CromosaMLabel8 = new javax.swing.JLabel();
        CromosaMLabel9 = new javax.swing.JLabel();
        CromosaMLabel10 = new javax.swing.JLabel();
        CromosaMLabel11 = new javax.swing.JLabel();
        resultadoTextField = new javax.swing.JTextField();
        resultadoTextField1 = new javax.swing.JTextField();
        resultadoTextField2 = new javax.swing.JTextField();
        resultadoTextField3 = new javax.swing.JTextField();
        resultadoTextField4 = new javax.swing.JTextField();
        resultadoTextField5 = new javax.swing.JTextField();
        resultadoTextField6 = new javax.swing.JTextField();
        resultadoTextField7 = new javax.swing.JTextField();
        resultadoTextField8 = new javax.swing.JTextField();
        resultadoTextField9 = new javax.swing.JTextField();
        resultadoTextField10 = new javax.swing.JTextField();
        resultadoTextField11 = new javax.swing.JTextField();
        separadorPanel = new javax.swing.JPanel();
        separadorPanel1 = new javax.swing.JPanel();
        separadorPanel3 = new javax.swing.JPanel();
        separadorPanel4 = new javax.swing.JPanel();
        separadorPanel2 = new javax.swing.JPanel();
        ideaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Cruses_MonoHibridos"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrusesMonoHibridoPanel.setBackground(new java.awt.Color(204, 255, 204));
        CrusesMonoHibridoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        CrusesMonoHibridoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        retornoButton.setBackground(new java.awt.Color(204, 255, 204));
        retornoButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        retornoButton.setForeground(new java.awt.Color(0, 0, 0));
        retornoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\atras.png")); // NOI18N
        retornoButton.setText("Menu de cruses");
        retornoButton.setToolTipText("");
        retornoButton.setActionCommand("retorno");
        retornoButton.setBorder(null);
        retornoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        retornoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        CrusesMonoHibridoPanel.add(retornoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 130, 30));

        MujerLabel.setBackground(new java.awt.Color(51, 51, 51));
        MujerLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        MujerLabel.setForeground(new java.awt.Color(0, 0, 0));
        MujerLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\icons8-mujer-de-negocios-34.png")); // NOI18N
        MujerLabel.setText(" Mujer");
        MujerLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrusesMonoHibridoPanel.add(MujerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 170, 30));

        BaronLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BaronLabel.setForeground(new java.awt.Color(0, 0, 0));
        BaronLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\icons8-tipo-de-piel-masculina-del-usuario-7-24.png")); // NOI18N
        BaronLabel.setText("   Varon");
        BaronLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrusesMonoHibridoPanel.add(BaronLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 30));

        ContenedorChecboxPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContenedorChecboxPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noportadoraCheckBox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        noportadoraCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        noportadoraCheckBox.setSelected(true);
        noportadoraCheckBox.setText("Sano(a) XU XU");
        noportadoraCheckBox.setActionCommand("sano");
        noportadoraCheckBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 255, 204), null, null));
        ContenedorChecboxPanel.add(noportadoraCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 26, 166, 48));

        sindromeCheckBox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sindromeCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        sindromeCheckBox.setText("Con sindrome Xu Xu");
        sindromeCheckBox.setActionCommand("sindrome");
        sindromeCheckBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContenedorChecboxPanel.add(sindromeCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 74, 166, -1));

        portadoraCheckBox.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        portadoraCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        portadoraCheckBox.setText("Portadora XU Xu");
        portadoraCheckBox.setActionCommand("portador");
        portadoraCheckBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContenedorChecboxPanel.add(portadoraCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 166, -1));

        CrusesMonoHibridoPanel.add(ContenedorChecboxPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 170, 100));

        ContenedorChecbox2Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ContenedorChecbox2Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sindromeRadioButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sindromeRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        sindromeRadioButton.setText("Con Sindrome XU Y");
        sindromeRadioButton.setActionCommand("sindrome");
        ContenedorChecbox2Panel.add(sindromeRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        sanoRadioButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        sanoRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        sanoRadioButton.setText("Sano(a) XU Y");
        sanoRadioButton.setActionCommand("sano");
        ContenedorChecbox2Panel.add(sanoRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        CrusesMonoHibridoPanel.add(ContenedorChecbox2Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 80));

        ContendorPunerPanel.setBackground(new java.awt.Color(0, 0, 0));
        ContendorPunerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SepadorLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\linea-diagonal.png")); // NOI18N
        SepadorLabel.setToolTipText("");
        ContendorPunerPanel.add(SepadorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        SexoFLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        SexoFLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\mujer.png")); // NOI18N
        ContendorPunerPanel.add(SexoFLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        SexoMLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\masculino.png")); // NOI18N
        SexoMLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ContendorPunerPanel.add(SexoMLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 30, 30));

        CromosaMLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 40, 40));

        CromosaMLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 40, 40));

        CromosaMLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\icons8-y-34.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 40, 60));

        CromosaMLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 40, 40));

        CromosaMLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, 40));

        CromosaMLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 40, 40));

        CromosaMLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 40, 40));

        CromosaMLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 40, 40));

        CromosaMLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 40, 40));

        CromosaMLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cromosoma X.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 40, 40));

        CromosaMLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\icons8-y-34.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 40, 60));

        CromosaMLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\icons8-y-34.png")); // NOI18N
        ContendorPunerPanel.add(CromosaMLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 40, 60));

        resultadoTextField.setEditable(false);
        resultadoTextField.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 30, 30));

        resultadoTextField1.setEditable(false);
        resultadoTextField1.setBackground(new java.awt.Color(255, 255, 255));
        ContendorPunerPanel.add(resultadoTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 30));

        resultadoTextField2.setEditable(false);
        resultadoTextField2.setBackground(new java.awt.Color(255, 255, 255));
        ContendorPunerPanel.add(resultadoTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 30, 30));

        resultadoTextField3.setEditable(false);
        resultadoTextField3.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, 30));

        resultadoTextField4.setEditable(false);
        resultadoTextField4.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 30, 30));

        resultadoTextField5.setEditable(false);
        resultadoTextField5.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 30, 30));

        resultadoTextField6.setEditable(false);
        resultadoTextField6.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 30, 30));

        resultadoTextField7.setEditable(false);
        resultadoTextField7.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 30, 30));

        resultadoTextField8.setEditable(false);
        resultadoTextField8.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 30, 30));

        resultadoTextField9.setEditable(false);
        resultadoTextField9.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 30, 30));

        resultadoTextField10.setEditable(false);
        resultadoTextField10.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 30, 30));

        resultadoTextField11.setEditable(false);
        resultadoTextField11.setBackground(new java.awt.Color(255, 255, 255));
        resultadoTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ContendorPunerPanel.add(resultadoTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 30, 30));
        ContendorPunerPanel.add(separadorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 10, 210));
        ContendorPunerPanel.add(separadorPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 10, 210));
        ContendorPunerPanel.add(separadorPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, -1));
        ContendorPunerPanel.add(separadorPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 340, 10));
        ContendorPunerPanel.add(separadorPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 200));

        CrusesMonoHibridoPanel.add(ContendorPunerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 400, 210));

        ideaButton.setBackground(new java.awt.Color(204, 255, 204));
        ideaButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\bombilla-ecologica.png")); // NOI18N
        ideaButton.setActionCommand("idea");
        CrusesMonoHibridoPanel.add(ideaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(CrusesMonoHibridoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaronLabel;
    private javax.swing.JPanel ContendorPunerPanel;
    private javax.swing.JPanel ContenedorChecbox2Panel;
    private javax.swing.JPanel ContenedorChecboxPanel;
    private javax.swing.JLabel CromosaMLabel;
    private javax.swing.JLabel CromosaMLabel1;
    private javax.swing.JLabel CromosaMLabel10;
    private javax.swing.JLabel CromosaMLabel11;
    private javax.swing.JLabel CromosaMLabel2;
    private javax.swing.JLabel CromosaMLabel3;
    private javax.swing.JLabel CromosaMLabel4;
    private javax.swing.JLabel CromosaMLabel5;
    private javax.swing.JLabel CromosaMLabel6;
    private javax.swing.JLabel CromosaMLabel7;
    private javax.swing.JLabel CromosaMLabel8;
    private javax.swing.JLabel CromosaMLabel9;
    private javax.swing.JPanel CrusesMonoHibridoPanel;
    private javax.swing.JLabel MujerLabel;
    private javax.swing.JLabel SepadorLabel;
    private javax.swing.JLabel SexoFLabel;
    private javax.swing.JLabel SexoMLabel;
    private javax.swing.JButton ideaButton;
    private javax.swing.JCheckBox noportadoraCheckBox;
    private javax.swing.JCheckBox portadoraCheckBox;
    private javax.swing.JTextField resultadoTextField;
    private javax.swing.JTextField resultadoTextField1;
    private javax.swing.JTextField resultadoTextField10;
    private javax.swing.JTextField resultadoTextField11;
    private javax.swing.JTextField resultadoTextField2;
    private javax.swing.JTextField resultadoTextField3;
    private javax.swing.JTextField resultadoTextField4;
    private javax.swing.JTextField resultadoTextField5;
    private javax.swing.JTextField resultadoTextField6;
    private javax.swing.JTextField resultadoTextField7;
    private javax.swing.JTextField resultadoTextField8;
    private javax.swing.JTextField resultadoTextField9;
    private javax.swing.JToggleButton retornoButton;
    private javax.swing.JRadioButton sanoRadioButton;
    private javax.swing.JPanel separadorPanel;
    private javax.swing.JPanel separadorPanel1;
    private javax.swing.JPanel separadorPanel2;
    private javax.swing.JPanel separadorPanel3;
    private javax.swing.JPanel separadorPanel4;
    private javax.swing.JCheckBox sindromeCheckBox;
    private javax.swing.JRadioButton sindromeRadioButton;
    // End of variables declaration//GEN-END:variables

   
 


   
}
