/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.OG.Views;

import com.OG.Controller.VentanaPrincipal_Controlador;
//import java.awt.event.WindowAdapter;
//import java.awt.event.WindowEvent;
//import java.beans.EventHandler;
//import javax.swing.WindowConstants;

/**
 *
 * @author acer
 */
public class ventana_principal extends javax.swing.JFrame {
 VentanaPrincipal_Controlador  ma;
    /**
     * Creates new form ventana_principal
     */
    public ventana_principal() {
        initComponents();
          Iniciar();
    }
       
   
  public final void Iniciar()
   {
   ma = new VentanaPrincipal_Controlador(this);  
   CruseMHButton1.addActionListener(ma);
   salidaButton.addActionListener(ma);
   CruseDhButton2.addActionListener(ma);
   this.dispose();
   }
    
    
    
  public void showChild(VentanaC_Monohibrida CrusesMonohibrido, boolean b)  
  {
    CrusesMonohibrido.setVisible(b);
    CrusesMonohibrido.setLocationRelativeTo(null);
    this.dispose();
   
  }
    
    
  public void howChild(VentanaC_Dihibridos CrusesDihibrido, boolean b) 
  {
     CrusesDihibrido.setVisible(b);
     CrusesDihibrido.setLocationRelativeTo(null);
     this.dispose();

  }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CrusesPanel = new javax.swing.JPanel();
        CruseMhLabel = new javax.swing.JLabel();
        CruseMHButton1 = new javax.swing.JButton();
        CruseDhButton2 = new javax.swing.JButton();
        salidaButton = new javax.swing.JButton();
        bombillaButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrusesPanel.setBackground(new java.awt.Color(102, 255, 255));
        CrusesPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CrusesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CruseMhLabel.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CruseMhLabel.setForeground(new java.awt.Color(0, 0, 0));
        CruseMhLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\biologia.png")); // NOI18N
        CrusesPanel.add(CruseMhLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        CruseMHButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CruseMHButton1.setForeground(new java.awt.Color(0, 0, 0));
        CruseMHButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\Cromosoma.png")); // NOI18N
        CruseMHButton1.setText("   Cruses Mono Hibrido");
        CruseMHButton1.setActionCommand("CruseMH");
        CrusesPanel.add(CruseMHButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, -1));

        CruseDhButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CruseDhButton2.setForeground(new java.awt.Color(0, 0, 0));
        CruseDhButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\estructura-del-adn.png")); // NOI18N
        CruseDhButton2.setText("   Cruses Dihibridos");
        CruseDhButton2.setActionCommand("CruseDh");
        CruseDhButton2.setAutoscrolls(true);
        CrusesPanel.add(CruseDhButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 230, -1));

        salidaButton.setBackground(new java.awt.Color(102, 255, 255));
        salidaButton.setForeground(new java.awt.Color(102, 255, 255));
        salidaButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\cerrar-sesion.png")); // NOI18N
        salidaButton.setActionCommand("salida");
        salidaButton.setBorder(null);
        CrusesPanel.add(salidaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 50, 30));

        bombillaButton1.setBackground(new java.awt.Color(102, 255, 255));
        bombillaButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Cruses_Mendelianos\\src\\main\\Recurse\\image\\bombilla-ecologica.png")); // NOI18N
        bombillaButton1.setActionCommand("bombilla");
        bombillaButton1.setBorder(null);
        CrusesPanel.add(bombillaButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 50, 30));

        getContentPane().add(CrusesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CruseDhButton2;
    private javax.swing.JButton CruseMHButton1;
    private javax.swing.JLabel CruseMhLabel;
    private javax.swing.JPanel CrusesPanel;
    private javax.swing.JButton bombillaButton1;
    private javax.swing.JButton salidaButton;
    // End of variables declaration//GEN-END:variables

  
    


 }
